[tool.poetry]
name = "hash-table"
version = "0.1.0"
description = ""
authors = ["Joel Grayson <thejoelgrayson@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"